# Generated by Django 6.0.4 on 2026-05-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donorprofile_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='city',
            field=models.CharField(blank=True, choices=[('Cairo', 'Cairo'), ('Alexandria', 'Alexandria'), ('Giza', 'Giza'), ('Shubra El Kheima', 'Shubra El Kheima'), ('Port Said', 'Port Said'), ('Suez', 'Suez'), ('Luxor', 'Luxor'), ('Aswan', 'Aswan'), ('Asyut', 'Asyut'), ('Mansoura', 'Mansoura'), ('Tanta', 'Tanta'), ('Zagazig', 'Zagazig'), ('Ismailia', 'Ismailia'), ('Faiyum', 'Faiyum'), ('Damietta', 'Damietta'), ('Minya', 'Minya'), ('Beni Suef', 'Beni Suef'), ('Qena', 'Qena'), ('Sohag', 'Sohag'), ('Hurghada', 'Hurghada'), ('Sharm El Sheikh', 'Sharm El Sheikh')], max_length=100, null=True),
        ),
    ]
