# Generated by Django 6.0.4 on 2026-05-04 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_donorprofile_latitude_donorprofile_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='donors.donorprofile')),
            ],
        ),
    ]
