# Generated by Django 6.0.4 on 2026-05-12 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0007_alter_donorprofile_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donorprofile',
            name='full_name',
        ),
    ]
