# Generated by Django 6.0.4 on 2026-05-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0008_remove_donorprofile_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
