# Generated by Django 6.0.4 on 2026-05-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0011_alter_donorprofile_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
