# Generated by Django 6.0.4 on 2026-05-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donor_last_donation_date'),
        ('requests_app', '0002_alter_bloodrequest_blood_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='accounts.hospitalprofile'),
        ),
    ]
