# Generated by Django 6.0.4 on 2026-05-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_patient_email_patient_username'),
        ('requests_app', '0004_patientprofile_latitude_patientprofile_longitude'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BloodRequest',
            new_name='PatientBloodRequest',
        ),
    ]
