# Generated by Django 6.0.4 on 2026-04-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_donor_no_chronic_diseases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
