# Generated by Django 6.0.4 on 2026-05-01 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_donor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
    ]
