# Generated by Django 6.0.4 on 2026-05-01 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_donor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='no_chronic_diseases',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='no_restrictive_diseases',
        ),
        migrations.AddField(
            model_name='donor',
            name='has_no_chronic_diseases',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='has_no_restrictive_diseases',
            field=models.BooleanField(default=True),
        ),
    ]
