# Generated by Django 6.0.4 on 2026-05-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donor_last_donation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalprofile',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='hospital_documents/licenses/'),
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='official_docs',
            field=models.FileField(blank=True, null=True, upload_to='hospital_documents/official_docs/'),
        ),
    ]
