# Generated by Django 6.0.4 on 2026-05-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_hospitalprofile_latitude_hospitalprofile_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='username',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
