# Generated by Django 6.0.4 on 2026-05-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_donor_email_donor_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='last_donation_date',
        ),
        migrations.AddField(
            model_name='donor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
