# Generated by Django 6.0.4 on 2026-05-04 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_donor_last_donation_date'),
        ('hospitals', '0002_alter_hospitalprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='bloodunit',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_units', to='accounts.hospitalprofile'),
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock'), ('NEW_REQUEST', 'New Blood Request'), ('CRITICAL_REQUEST', 'Critical Request'), ('DONOR_AVAILABLE', 'Donor Available')], max_length=30)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='accounts.hospitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('available_units', models.PositiveIntegerField()),
                ('expiry_date', models.DateField()),
                ('city', models.CharField(max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('TRANSFERRED', 'Transferred'), ('CANCELLED', 'Cancelled')], default='AVAILABLE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blood_offers', to='accounts.hospitalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BloodRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_by', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('PATIENT', 'Patient')], max_length=20)),
                ('patient_name', models.CharField(blank=True, max_length=150, null=True)),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('required_units', models.PositiveIntegerField(default=1)),
                ('urgency', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('hospital_address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_blood_requests', to='accounts.hospitalprofile')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blood_requests', to='accounts.patient')),
            ],
        ),
    ]
