# Generated by Django 6.0.4 on 2026-05-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_remove_hospitalprofile_user_alter_bloodunit_hospital_and_more'),
        ('requests_app', '0003_alter_bloodrequest_hospital'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HospitalProfile',
        ),
    ]
