# Generated by Django 6.0.4 on 2026-05-05 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_donoractivity'),
        ('hospitals', '0004_delete_hospitalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='target_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_requests', to='donors.donorprofile'),
        ),
    ]
