# Generated by Django 6.0.4 on 2026-05-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0005_bloodrequest_target_donor'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
