# Generated by Django 6.0.4 on 2026-05-11 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0007_hospitalappointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BloodOffer',
        ),
    ]
