# Generated by Django 6.0.4 on 2026-05-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_delete_bloodoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodunit',
            name='units',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
