# Generated by Django 6.0.4 on 2026-05-12 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_bloodunit_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodunit',
            name='source',
            field=models.CharField(choices=[('Collected', 'Collected'), ('Manual', 'Manual'), ('Donation', 'Donation')], default='Manual', max_length=20),
        ),
    ]
