# Generated by Django 6.0.4 on 2026-05-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_bloodunit_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodunit',
            name='unit_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
