# Generated by Django 6.0.4 on 2026-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0011_alter_bloodunit_unit_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
